### ISSUE TITLE
Any plans to support writing out a graph directly via `Display`?

### ISSUE THREAD

**Issue by JustusAdam** [facebookexperimental/allocative#8]
Right now you always have to convert the graph to a `String` and then write it. Wouldn't it be more efficient to instead implement `Display` so it can be directly written to a file or other I/O stream?

**Comment by stepancheg** [comment]
Writing to string is cheap compared to graph traversal.

Especially when the graph is large — because the resulting string is small compared to traversed graph: output contains only unique paths, not all the paths.

So, no plans, unless you know a good reason to do it.

**Comment by JustusAdam** [comment]
Sorry I don't think I quite understand. You also traverse the graph when writing to a String here https://github.com/facebookexperimental/allocative/blob/54780c3037c9efd1b1875dcb869fc4959e7ac255/allocative/src/flamegraph.rs#L67. You could just as well be writing to a `std::fmt::Formatter`, thus eliding the intermediate string.

**Comment by stepancheg** [comment]
I understand writing to `Formatting` is potentially cheaper when writing to a file rather than writing to intermediate `String`.

But it will be like 0.01% cheaper overall, which is not worth the trouble. No?

**Comment by JustusAdam** [comment]
Perhaps, but the implementation as far as I can see already only uses `writeln`, so the only change that would need to happen is to change the type signature of https://github.com/facebookexperimental/allocative/blob/54780c3037c9efd1b1875dcb869fc4959e7ac255/allocative/src/flamegraph.rs#L67 to take `&mut Formatter<'_>` instead of `&mut String`. Using `Display` just feels more "rusty" to me than returning a string.
